/* Captures the three reference artifacts out of a running page.
 *
 * The tool runs in a browser, so the reference has to be taken from a browser —
 * the PNG in particular comes out of canvas.toBlob and nothing outside the
 * browser produces the same bytes.
 *
 * Procedure:
 *   1.  powershell -File .claude\serve.ps1 -Port 8791
 *   2.  open http://127.0.0.1:8791/
 *   3.  paste this whole file into the console
 *   4.  await __captureAll()
 *
 * Each artifact is POSTed to /save/<name>, which serve.ps1 writes into
 * .claude/shots/. Move them to test/golden/ to promote them to references, or
 * leave them there and run:
 *
 *   powershell -File test\compare-golden.ps1
 *
 * The PNG is taken through the same path as the "Download PNG" button: full
 * resolution when the full buffer survived, the display copy otherwise.
 */

window.__capture = async function (name) {
  var st = window.__state;
  if (!st || !st.diag) throw new Error('nothing loaded');

  async function sha(buf) {
    var h = await crypto.subtle.digest('SHA-256', buf);
    return Array.from(new Uint8Array(h)).map(function (b) { return b.toString(16).padStart(2, '0'); }).join('');
  }
  async function post(fname, blob) {
    var ab = await blob.arrayBuffer();
    await fetch('/save/' + fname, { method: 'POST', body: ab });
    return { file: fname, bytes: ab.byteLength, sha256: await sha(ab) };
  }

  var data, w, h;
  if (st.full) { data = st.full; w = st.w; h = st.h; }
  else { data = st.view.data; w = st.view.w; h = st.view.h; }

  var c = document.createElement('canvas');
  c.width = w; c.height = h;
  c.getContext('2d').putImageData(new ImageData(data, w, h), 0, 0);
  var png = await new Promise(function (res) { c.toBlob(res, 'image/png'); });

  return {
    log:  await post(name + '.log.txt',   new Blob([st.log])),
    diag: await post(name + '.diag.json', new Blob([JSON.stringify(st.diag, null, 2)])),
    // The per-step, per-channel measurements — before and after every step that
    // touched pixels. This is what survives the day the PNG stops being
    // byte-comparable, which is the day a second step joins the chain.
    records: await post(name + '.records.json', new Blob([JSON.stringify(st.records, null, 2)])),
    png:  await post(name + '.png', png)
  };
};

// The date the log prints. Pinned, because the log carries it and a golden that
// moves with the calendar is not a golden. Never change it: changing it
// invalidates every stored log, for no gain.
window.__GOLDEN_DATE = '2026-09-05';

// The reference set. Paths are served by serve.ps1's /f/ route, which maps
// anything under stretch-tool/.
//
// Every one of these is synthetic, generated by .claude/make-fixture.ps1 from a
// fixed seed. No frame from anyone else is ever added here — see CLAUDE.md.
window.__GOLDEN = [
  ['seestar-fixture',   '/f/test/fixtures/fixture-seestar.fit'],
  ['rice-fixture',      '/f/test/fixtures/fixture-rice.fit.fz'],
  ['nonlinear-fixture', '/f/test/fixtures/fixture-nonlinear.fit'],
  // Module 1. Nothing in the chain reads its gradient yet, so today this
  // golden only pins the decode and the autostretch of a 1600x1200 frame. It
  // is captured now anyway: when background extraction lands, "what changed"
  // has to be answerable against a baseline taken before it existed.
  ['gradient-fixture',  '/f/test/fixtures/fixture-gradient.fit']
];

window.__captureAll = async function () {
  var out = {};
  for (var i = 0; i < window.__GOLDEN.length; i++) {
    var name = window.__GOLDEN[i][0], url = window.__GOLDEN[i][1];
    var r = await window.__loadFromURL(url, { now: window.__GOLDEN_DATE });
    if (r !== 'ok') throw new Error(name + ': ' + url + ' failed to load');
    out[name] = await window.__capture(name);
  }
  return out;
};
