/* Captures the three reference artifacts out of a running page.
 *
 * The tool runs in a browser, so the reference has to be taken from a browser —
 * the PNG in particular comes out of canvas.toBlob and nothing outside the
 * browser produces the same bytes.
 *
 * Procedure:
 *   1.  powershell -File .claude\serve.ps1 -Port 8791
 *   2.  open http://127.0.0.1:8791/
 *   3.  paste this whole file into the console
 *   4.  await __captureAll()
 *
 * Each artifact is POSTed to /save/<name>, which serve.ps1 writes into
 * .claude/shots/. Move them to test/golden/ to promote them to references, or
 * leave them there and run:
 *
 *   powershell -File test\compare-golden.ps1
 *
 * The PNG is taken through the same path as the "Download PNG" button: full
 * resolution when the full buffer survived, the display copy otherwise.
 */

window.__capture = async function (name) {
  var st = window.__state;
  if (!st || !st.diag) throw new Error('nothing loaded');

  async function sha(buf) {
    var h = await crypto.subtle.digest('SHA-256', buf);
    return Array.from(new Uint8Array(h)).map(function (b) { return b.toString(16).padStart(2, '0'); }).join('');
  }
  async function post(fname, blob) {
    var ab = await blob.arrayBuffer();
    await fetch('/save/' + fname, { method: 'POST', body: ab });
    return { file: fname, bytes: ab.byteLength, sha256: await sha(ab) };
  }

  var data, w, h;
  if (st.full) { data = st.full; w = st.w; h = st.h; }
  else { data = st.view.data; w = st.view.w; h = st.view.h; }

  var c = document.createElement('canvas');
  c.width = w; c.height = h;
  c.getContext('2d').putImageData(new ImageData(data, w, h), 0, 0);
  var png = await new Promise(function (res) { c.toBlob(res, 'image/png'); });

  return {
    log:  await post(name + '.log.txt',   new Blob([st.log])),
    diag: await post(name + '.diag.json', new Blob([JSON.stringify(st.diag, null, 2)])),
    // The per-step, per-channel measurements — before and after every step that
    // touched pixels. This is what survives the day the PNG stops being
    // byte-comparable, which is the day a second step joins the chain.
    records: await post(name + '.records.json', new Blob([JSON.stringify(st.records, null, 2)])),
    png:  await post(name + '.png', png)
  };
};

// The date the log prints. Pinned, because the log carries it and a golden that
// moves with the calendar is not a golden. Never change it: changing it
// invalidates every stored log, for no gain.
window.__GOLDEN_DATE = '2026-09-05';

// The reference set. Paths are served by serve.ps1's /f/ route, which maps
// anything under stretch-tool/.
//
// Every one of these is synthetic, generated by .claude/make-fixture.ps1 from a
// fixed seed. No frame from anyone else is ever added here — see CLAUDE.md.
window.__GOLDEN = [
  ['seestar-fixture',   '/f/test/fixtures/fixture-seestar.fit'],
  ['rice-fixture',      '/f/test/fixtures/fixture-rice.fit.fz'],
  ['nonlinear-fixture', '/f/test/fixtures/fixture-nonlinear.fit'],
  // Module 1. Nothing in the chain reads its gradient yet, so today this
  // golden only pins the decode and the autostretch of a 1600x1200 frame. It
  // is captured now anyway: when background extraction lands, "what changed"
  // has to be answerable against a baseline taken before it existed.
  ['gradient-fixture',  '/f/test/fixtures/fixture-gradient.fit'],
  // 400x300, o unico pequeno o bastante para a margem padrao alcancar a
  // grade de amostras. Existe para que rejected-edge seja exercitado e nao
  // apenas alcancavel.
  ['edge-fixture',      '/f/test/fixtures/fixture-edge.fit'],
  // Modulo 2. O unico fixture com cor conhecida por construcao, e o unico
  // capturado com parametros que nao sao os defaults: colourCal esta desligado
  // por padrao ate o Modulo 3, entao capturar com os defaults nao exercitaria
  // nada da calibracao. Os parametros vao pelo mesmo requestRun que a interface
  // usaria; nao ha caminho de teste separado.
  ['colour-fixture',    '/f/test/fixtures/fixture-colour.fit', { colourCal: true }],
  // Modulo 3 passo 6. O mesmo quadro do gradient, pelo outro operador, para que
  // o asinh esteja verificado e nao apenas escrito. Nao e o padrao: a decisao de
  // trocar espera haver imagem real para comparar. O que este golden fixa e a
  // resolucao numerica de `stretch` contra o alvo -- 171.998 neste quadro, que e
  // o numero que faz o asinh responder ao mesmo alvo que o MTF responde.
  ['asinh-fixture',     '/f/test/fixtures/fixture-gradient.fit', { operator: 'asinh' }],
  // Modulo 4. Os dois unicos com saturacao ligada: ela e opcional e desligada
  // por padrao, entao capturar com os defaults nao exercitaria nada dela.
  // O flatsky nao tem objeto nenhum -- todo pixel abaixo do limiar de SNR --
  // e existe para que a etapa tenha um quadro onde o certo e nao tocar em nada.
  ['saturation-fixture', '/f/test/fixtures/fixture-saturation.fit', { saturation: true }],
  ['flatsky-fixture',    '/f/test/fixtures/fixture-flatsky.fit',    { saturation: true }],
  // Modulo 5a passo 4. Os dois casos que fazem as salvaguardas do recorte
  // recusarem, e os dois com LARGURA IMPAR (1601) -- que e o que exercita o
  // descarte de coluna da meia escala, deixado sem caso pelo passo 1.
  ['twoobjects-fixture', '/f/test/fixtures/fixture-twoobjects.fit'],
  ['bigobject-fixture',  '/f/test/fixtures/fixture-bigobject.fit'],
  ['oneobject-fixture',  '/f/test/fixtures/fixture-oneobject.fit'],
  // O TERCEIRO ESTADO do recorte: aplicado. O unico golden com cropApply, e o
  // unico caso permanente em que a palavra 'cropping' SAI da frase -- porque a
  // ferramenta recortou. Sem ele o estado existe no codigo e nao na suite.
  ['cropped-fixture',    '/f/test/fixtures/fixture-oneobject.fit', { cropApply: true }]
];

/* ------------------------------------------------------------------ *
 * The malformed corpus
 *
 * Files that lie about themselves: impossible geometry, a BITPIX outside the
 * standard, a header with no END, a .fz whose table points outside the file.
 * Generated by test/make-malformed.ps1, which explains in its own header why
 * they are not versioned when the fixtures are.
 *
 * What is recorded is the VERDICT, not pixels: rejected with which error kind,
 * or accepted with which dimensions. The question the file answers is "does
 * this stay rejected?", and the failure that matters is silent acceptance —
 * a file that used to be refused and now produces a picture.
 *
 * Read straight through the decode entry points rather than through the UI:
 * the outcome wanted here is the error kind, and the worker path deliberately
 * drops the detail message before it reaches the screen.
 * ------------------------------------------------------------------ */
window.__captureMalformed = async function () {
  var src = document.getElementById('pipeline-src').textContent;
  var shim = { onmessage: null, postMessage: function () {} };
  new Function('self', src + ';self.__M={findImageHDU:findImageHDU,' +
    'toNormalisedFloat:toNormalisedFloat,decodeTileCompressed:decodeTileCompressed};')(shim);
  var M = shim.__M;

  var list = await fetch('/f/test/golden/malformed.json').then(function (r) { return r.json(); });
  var names = Object.keys(list.casos).sort();
  var out = {};

  for (var i = 0; i < names.length; i++) {
    var f = names[i];
    var buf = await fetch('/f/test/malformed/' + f).then(function (r) { return r.arrayBuffer(); });
    var t0 = performance.now();
    var row;
    try {
      var hdu = M.findImageHDU(buf);
      var d = hdu.compressed ? M.decodeTileCompressed(buf, hdu, function () {}, null)
                             : M.toNormalisedFloat(buf, hdu, function () {});
      row = { veredito: 'aceita', dims: d.w + 'x' + d.h + 'x' + d.planes };
    } catch (e) {
      row = { veredito: 'rejeita', kind: (e && e.kind) || (e && e.constructor && e.constructor.name) || 'sem-kind',
              mensagem: String((e && e.message) || e) };
    }
    // Sub-millisecond everywhere today. Recorded because "it stopped" is half
    // the claim: a file that hangs the tab fails differently from one that
    // errors, and the number is what tells them apart.
    row.ms = Math.round(performance.now() - t0);
    row.bytes = buf.byteLength;
    out[f] = row;
  }

  var body = new Blob([JSON.stringify({ casos: out }, null, 2)]);
  var ab = await body.arrayBuffer();
  await fetch('/save/malformed.results.json', { method: 'POST', body: ab });
  return { casos: names.length, arquivo: 'malformed.results.json', bytes: ab.byteLength };
};

// Re-runs the chain with parameters that are not the defaults, through the same
// requestRun the interface uses. Waits on the result panel rather than on a
// promise, because requestRun is fire-and-forget by design: the host is a UI and
// its answer arrives as a repainted screen.
window.__rerun = function (over) {
  var params = {}, k;
  for (k in window.__state.defaults) params[k] = window.__state.defaults[k];
  for (k in over) params[k] = over[k];
  window.__state.diag = null;
  requestRun(params, 'full');
  return new Promise(function (resolve, reject) {
    var waited = 0;
    var iv = setInterval(function () {
      if (window.__state.diag) { clearInterval(iv); resolve('ok'); return; }
      if (document.getElementById('err').classList.contains('on')) {
        clearInterval(iv);
        reject(new Error(document.getElementById('errtitle').textContent));
        return;
      }
      if ((waited += 250) > 120000) { clearInterval(iv); reject(new Error('rerun timed out')); }
    }, 250);
  });
};


/* ------------------------------------------------------------------ *
 * A salvaguarda de estabilidade, exercitada nos dois lados
 *
 * A regra dos ganhos e: um erro de 10% no ceu pode mover qualquer ganho em no
 * maximo 5%. Depois que ela substituiu a regra dos 3x, NENHUM fixture a faz
 * disparar -- todos ficam entre 0,03% e 1,3%. Uma salvaguarda que nunca
 * dispara e uma salvaguarda que ninguem verificou, e isso ja custou uma
 * sessao aqui com os quatro zeros do `rejected-edge`.
 *
 * Somar uma constante ao quadro nao muda `above` (o pedestal e a mediana
 * estelar sobem juntos) mas AUMENTA a sondagem, que e 10% do pedestal. E o
 * caso fisico exato que a regra existe para pegar: ceu alto contra estrela
 * fraca. A varredura tem que passar de APLICA para RECUSA, e a sensibilidade
 * tem que crescer monotonicamente ate la.
 * ------------------------------------------------------------------ */
window.__captureSafeguards = async function () {
  var src = document.getElementById('pipeline-src').textContent;
  var shim = { onmessage: null, postMessage: function () {} };
  new Function('self', src + ';self.__S={findImageHDU:findImageHDU,' +
    'toNormalisedFloat:toNormalisedFloat,Image:Image,' +
    'stepBackground:stepBackground,stepColourCal:stepColourCal};')(shim);
  var S = shim.__S;

  var passos = [0, 0.05, 0.10, 0.15, 0.20, 0.30];
  var casos = [];
  for (var i = 0; i < passos.length; i++) {
    var C = passos[i];
    var buf = await fetch('/f/test/fixtures/fixture-gradient.fit').then(function (r) { return r.arrayBuffer(); });
    var hdu = S.findImageHDU(buf);
    var d = S.toNormalisedFloat(buf, hdu, function () {});
    var dat = new Float32Array(d.data);
    for (var k = 0; k < dat.length; k++) dat[k] += C;
    var img = new S.Image(dat, d.w, d.h, d.planes);
    var r1 = [];
    var bg = S.stepBackground(img, { samplesPerRow: 12, boxSize: 25, tolerance: 1.0,
      edgeMargin: 0.02, smoothing: 0.10, correction: 'subtract',
      pedestal: 'model-median', scale: 1, stride: 1 }, function (x) { r1.push(x); });
    var r2 = [];
    S.stepColourCal(bg, { backgroundNeutralise: true, starSigma: 12.0, starMax: 0.85,
      minStarPixels: 2000, extendedWindow: 25, extendedFrac: 0.50,
      reference: 'green', stride: 1 }, function (x) { r2.push(x); });
    var st = r2[0].stars;
    casos.push({
      ceuAdicionado: C,
      pedestal: st.pedestals ? st.pedestals[1] : null,
      sensibilidade: st.gainSensitivity,
      canal: st.gainSensitivityChannel,
      veredito: st.applied ? 'aplica' : 'recusa',
      ganhos: r2[0].gains || null
    });
  }
  // A salvaguarda da saturacao vai no MESMO arquivo, porque e o mesmo tipo de
  // afirmacao -- uma regra que so vale se alguem ja a viu recusar -- e um
  // comparador so evita que uma das duas fique orfa.
  var sat = await window.__captureSatSafeguards();

  var body = new Blob([JSON.stringify({ casos: casos, saturacao: sat }, null, 2)]);
  var ab = await body.arrayBuffer();
  await fetch('/save/safeguards.results.json', { method: 'POST', body: ab });
  return { casos: casos.length, saturacao: sat.casos.length, arquivo: 'safeguards.results.json' };
};


/* ------------------------------------------------------------------ *
 * A salvaguarda de ruido de croma da saturacao, exercitada de verdade
 *
 * A secao 2.4 do Modulo 4 pede: meca o desvio padrao da crominancia nos pixels
 * com snr < snrLow, antes e depois, e recuse se crescer mais de 2%. Com o
 * codigo certo ela NAO PODE disparar -- naqueles pixels o `w` satura em 0,
 * `k` e exatamente 1, e a crominancia nao e tocada. O crescimento medido e
 * -0,00%, que e tambem o que sai quando a etapa nao faz nada.
 *
 * Uma salvaguarda que nunca dispara e uma salvaguarda que ninguem verificou.
 * Este projeto ja pagou por isso duas vezes -- os quatro zeros do
 * `rejected-edge`, e a regra dos 3x que so foi vista disparando depois de
 * publicada. O caso aqui e o controle negativo: uma fonte deliberadamente
 * quebrada, rodada pela MESMA cadeia, que tem que fazer a etapa RECUSAR.
 *
 * DUAS ALAVANCAS ERRADAS FORAM TENTADAS ANTES, e o motivo de cada uma falhar
 * esta no NOTAS porque nao e obvio:
 *
 *   baixar `snrLow`   nao dispara: o conjunto medido pela salvaguarda E o
 *                     conjunto protegido pela mascara -- os dois leem o mesmo
 *                     limiar. Baixar o limiar esvazia o conjunto medido
 *                     (`pixels: 0`) em vez de desproteger alguem.
 *   ceu sem sinal     nao dispara: um quadro todo abaixo do limiar deixa TODO
 *                     mundo em k = 1. Protege tudo, que e o oposto de falhar.
 *
 * A alavanca certa e a FIACAO da mascara, nao um parametro: com o clamp do `w`
 * invertido, o fundo passa a receber o amount inteiro e a crominancia do ceu
 * cresce ~45%. E a falha que a regra existe para pegar, e nenhum ajuste de
 * parametro a produz.
 *
 * O TERCEIRO CASO mede o que a salvaguarda de ruido NAO pega. Escalar o azul
 * por um k diferente dos outros dois nao muda a magnitude da crominancia do
 * fundo o bastante para acusar -- a pre-passada nem ve, porque a quebra esta so
 * no laco principal -- e muda o MATIZ. Quem pega e a outra verificacao. As duas
 * juntas cobrem o que cada uma sozinha deixa passar; e por isso que sao duas.
 * ------------------------------------------------------------------ */

// As ancoras dos controles negativos. Sao strings da fonte publicada, e o
// comparador exige que cada uma apareca EXATAMENTE UMA VEZ: se alguem duplicar
// a aritmetica do `k` de novo, a contagem vira 2 e o teste reprova antes de
// olhar qualquer numero. Foi assim que a duplicacao original apareceu -- a
// pre-passada tinha a sua propria copia da formula, o clamp quebrado atingiu so
// o laco principal, e a copia intacta aprovou a mascara quebrada.
window.__SAT_ANCORAS = {
  clamp:    'if (w < 0) w = 0; else if (w > 1) w = 1;',
  clampInv: 'if (w < 0) w = 1; else if (w > 1) w = 0;',
  azul:     'var Bo = y + (B - y) * k;',
  azulOff:  'var Bo = y + (B - y) * k * 1.02;'
};

window.__captureSatSafeguards = async function () {
  var src = document.getElementById('pipeline-src').textContent;
  var A = window.__SAT_ANCORAS;

  function conta(hay, needle){ return hay.split(needle).length - 1; }
  function troca(hay, de, para){
    var n = conta(hay, de);
    if (n !== 1) throw new Error('ancora aparece ' + n + 'x, esperava 1: ' + de);
    return hay.split(de).join(para);
  }

  function monta(source){
    var shim = { onmessage: null, postMessage: function () {} };
    new Function('self', source + ';self.__T={findImageHDU:findImageHDU,' +
      'toNormalisedFloat:toNormalisedFloat,Image:Image,measure:measure,' +
      'stepBackground:stepBackground,stepColourCal:stepColourCal,' +
      'stepStretch:stepStretch,stepSaturation:stepSaturation};')(shim);
    return shim.__T;
  }

  /* A MESMA cadeia que o golden `saturation-fixture` roda, com os mesmos
   * defaults: fundo, cor, esticamento, e so entao a saturacao. A mascara le SNR
   * de um quadro JA ESTICADO -- medi-la em dado linear seria exercitar outra
   * etapa e chamar o resultado de controle desta. */
  async function rodar(T, url){
    // Buffer novo a cada rodada: toNormalisedFloat troca os bytes NO LUGAR, e
    // reaproveitar o mesmo ArrayBuffer ja produziu uma conclusao falsa aqui.
    var buf = await fetch(url).then(function (r) { return r.arrayBuffer(); });
    var hdu = T.findImageHDU(buf);
    var d = T.toNormalisedFloat(buf, hdu, function () {});
    var img = new T.Image(d.data, d.w, d.h, d.planes);

    var recs = [];
    function rep(x){ recs.push(x); }

    // A mesma regra de run.js, sem o ramo do HISTORY: os fixtures sao gerados
    // por make-fixture.ps1 e nao carregam historico de esticamento. Registrado
    // na saida para que uma mudanca no fixture que vire este bit apareca.
    var ms = T.measure(img, 1), gm = 0, c;
    for (c = 0; c < ms.perChannel.length; c++) gm += ms.perChannel[c].median;
    gm /= ms.perChannel.length;
    var naoLinear = (gm >= 0.05);

    img = T.stepBackground(img, { samplesPerRow: 12, boxSize: 25, tolerance: 1.0,
      edgeMargin: 0.02, smoothing: 0.10, correction: 'subtract',
      pedestal: 'model-median', scale: 1, stride: 1 }, rep);
    img = T.stepColourCal(img, { backgroundNeutralise: true, starSigma: 12.0,
      starMax: 0.85, minStarPixels: 2000, extendedWindow: 25, extendedFrac: 0.50,
      reference: 'green', stride: 1 }, rep);
    img = T.stepStretch(img, { linked: true, operator: 'mtf', stretch: null,
      shadowSigma: -2.80, target: 0.085, blackPct: 0.0005,
      nonLinear: naoLinear, stride: 1 }, rep);
    img = T.stepSaturation(img, { amount: 1.45, snrLow: 3.0, snrHigh: 25.0,
      highlightKnee: 0.80, highlightFloor: 0.35, stride: 1 }, rep);

    var s = null;
    for (var i = 0; i < recs.length; i++) if (recs[i].id === 'saturation') s = recs[i];
    if (!s) throw new Error('a etapa de saturacao nao reportou');
    return { rec: s, naoLinear: naoLinear };
  }

  var FIXTURE = '/f/test/fixtures/fixture-saturation.fit';

  var fontes = [
    { nome: 'codigo-publicado',   src: src },
    { nome: 'clamp-do-w-invertido', src: troca(src, A.clamp, A.clampInv) },
    { nome: 'azul-com-k-proprio',   src: troca(src, A.azul,  A.azulOff) }
  ];

  var casos = [];
  for (var i = 0; i < fontes.length; i++){
    var T = monta(fontes[i].src);
    var r = await rodar(T, FIXTURE);
    var rec = r.rec, cn = rec.chromaNoise || {}, hf = rec.hueFidelity, mk = rec.mask;
    casos.push({
      nome: fontes[i].nome,
      naoLinear: r.naoLinear,
      veredito: rec.applied ? 'aplica' : 'recusa',
      motivo: rec.skipReason,
      crescimentoPct: (cn.growthPct === undefined) ? null : cn.growthPct,
      limitePct: (cn.limitPct === undefined) ? null : cn.limitPct,
      pixelsDeFundo: (cn.pixels === undefined) ? null : cn.pixels,
      pctAbaixoDoLimiar: mk ? mk.pctBelowSnrLow : null,
      maxK: mk ? mk.maxK : null,
      mediaK: mk ? mk.meanK : null,
      derivaMatiz: hf ? hf.maxHueDrift : null,
      limiteMatiz: hf ? hf.limit : null,
      matizDentroDoLimite: hf ? hf.withinLimit : null
    });
  }

  return {
    // Estrutural, e vale antes de qualquer numero: UMA copia da formula do `k`.
    copiasDoClamp: conta(src, A.clamp),
    fixture: FIXTURE,
    casos: casos
  };
};

window.__captureAll = async function () {
  var out = {};
  for (var i = 0; i < window.__GOLDEN.length; i++) {
    var name = window.__GOLDEN[i][0], url = window.__GOLDEN[i][1], over = window.__GOLDEN[i][2];
    var r = await window.__loadFromURL(url, { now: window.__GOLDEN_DATE });
    if (r !== 'ok') throw new Error(name + ': ' + url + ' failed to load');
    if (over) await window.__rerun(over);
    out[name] = await window.__capture(name);
  }
  out['malformed'] = await window.__captureMalformed();
  out['safeguards'] = await window.__captureSafeguards();
  return out;
};
