/* Captures the three reference artifacts out of a running page.
 *
 * The tool runs in a browser, so the reference has to be taken from a browser —
 * the PNG in particular comes out of canvas.toBlob and nothing outside the
 * browser produces the same bytes.
 *
 * Procedure:
 *   1.  powershell -File .claude\serve.ps1 -Port 8791
 *   2.  open http://127.0.0.1:8791/
 *   3.  paste this whole file into the console
 *   4.  await __captureAll()
 *
 * Each artifact is POSTed to /save/<name>, which serve.ps1 writes into
 * .claude/shots/. Move them to test/golden/ to promote them to references, or
 * leave them there and run:
 *
 *   powershell -File test\compare-golden.ps1
 *
 * The PNG is taken through the same path as the "Download PNG" button: full
 * resolution when the full buffer survived, the display copy otherwise.
 */

window.__capture = async function (name) {
  var st = window.__state;
  if (!st || !st.diag) throw new Error('nothing loaded');

  async function sha(buf) {
    var h = await crypto.subtle.digest('SHA-256', buf);
    return Array.from(new Uint8Array(h)).map(function (b) { return b.toString(16).padStart(2, '0'); }).join('');
  }
  async function post(fname, blob) {
    var ab = await blob.arrayBuffer();
    await fetch('/save/' + fname, { method: 'POST', body: ab });
    return { file: fname, bytes: ab.byteLength, sha256: await sha(ab) };
  }

  var data, w, h;
  if (st.full) { data = st.full; w = st.w; h = st.h; }
  else { data = st.view.data; w = st.view.w; h = st.view.h; }

  var c = document.createElement('canvas');
  c.width = w; c.height = h;
  c.getContext('2d').putImageData(new ImageData(data, w, h), 0, 0);
  var png = await new Promise(function (res) { c.toBlob(res, 'image/png'); });

  return {
    log:  await post(name + '.log.txt',   new Blob([st.log])),
    diag: await post(name + '.diag.json', new Blob([JSON.stringify(st.diag, null, 2)])),
    // The per-step, per-channel measurements — before and after every step that
    // touched pixels. This is what survives the day the PNG stops being
    // byte-comparable, which is the day a second step joins the chain.
    records: await post(name + '.records.json', new Blob([JSON.stringify(st.records, null, 2)])),
    png:  await post(name + '.png', png)
  };
};

// The date the log prints. Pinned, because the log carries it and a golden that
// moves with the calendar is not a golden. Never change it: changing it
// invalidates every stored log, for no gain.
window.__GOLDEN_DATE = '2026-09-05';

// The reference set. Paths are served by serve.ps1's /f/ route, which maps
// anything under stretch-tool/.
//
// Every one of these is synthetic, generated by .claude/make-fixture.ps1 from a
// fixed seed. No frame from anyone else is ever added here — see CLAUDE.md.
window.__GOLDEN = [
  ['seestar-fixture',   '/f/test/fixtures/fixture-seestar.fit'],
  ['rice-fixture',      '/f/test/fixtures/fixture-rice.fit.fz'],
  ['nonlinear-fixture', '/f/test/fixtures/fixture-nonlinear.fit'],
  // Module 1. Nothing in the chain reads its gradient yet, so today this
  // golden only pins the decode and the autostretch of a 1600x1200 frame. It
  // is captured now anyway: when background extraction lands, "what changed"
  // has to be answerable against a baseline taken before it existed.
  ['gradient-fixture',  '/f/test/fixtures/fixture-gradient.fit'],
  // 400x300, o unico pequeno o bastante para a margem padrao alcancar a
  // grade de amostras. Existe para que rejected-edge seja exercitado e nao
  // apenas alcancavel.
  ['edge-fixture',      '/f/test/fixtures/fixture-edge.fit'],
  // Modulo 2. O unico fixture com cor conhecida por construcao, e o unico
  // capturado com parametros que nao sao os defaults: colourCal esta desligado
  // por padrao ate o Modulo 3, entao capturar com os defaults nao exercitaria
  // nada da calibracao. Os parametros vao pelo mesmo requestRun que a interface
  // usaria; nao ha caminho de teste separado.
  ['colour-fixture',    '/f/test/fixtures/fixture-colour.fit', { colourCal: true }],
  // Modulo 3 passo 6. O mesmo quadro do gradient, pelo outro operador, para que
  // o asinh esteja verificado e nao apenas escrito. Nao e o padrao: a decisao de
  // trocar espera haver imagem real para comparar. O que este golden fixa e a
  // resolucao numerica de `stretch` contra o alvo -- 171.998 neste quadro, que e
  // o numero que faz o asinh responder ao mesmo alvo que o MTF responde.
  ['asinh-fixture',     '/f/test/fixtures/fixture-gradient.fit', { operator: 'asinh' }]
];

/* ------------------------------------------------------------------ *
 * The malformed corpus
 *
 * Files that lie about themselves: impossible geometry, a BITPIX outside the
 * standard, a header with no END, a .fz whose table points outside the file.
 * Generated by test/make-malformed.ps1, which explains in its own header why
 * they are not versioned when the fixtures are.
 *
 * What is recorded is the VERDICT, not pixels: rejected with which error kind,
 * or accepted with which dimensions. The question the file answers is "does
 * this stay rejected?", and the failure that matters is silent acceptance —
 * a file that used to be refused and now produces a picture.
 *
 * Read straight through the decode entry points rather than through the UI:
 * the outcome wanted here is the error kind, and the worker path deliberately
 * drops the detail message before it reaches the screen.
 * ------------------------------------------------------------------ */
window.__captureMalformed = async function () {
  var src = document.getElementById('pipeline-src').textContent;
  var shim = { onmessage: null, postMessage: function () {} };
  new Function('self', src + ';self.__M={findImageHDU:findImageHDU,' +
    'toNormalisedFloat:toNormalisedFloat,decodeTileCompressed:decodeTileCompressed};')(shim);
  var M = shim.__M;

  var list = await fetch('/f/test/golden/malformed.json').then(function (r) { return r.json(); });
  var names = Object.keys(list.casos).sort();
  var out = {};

  for (var i = 0; i < names.length; i++) {
    var f = names[i];
    var buf = await fetch('/f/test/malformed/' + f).then(function (r) { return r.arrayBuffer(); });
    var t0 = performance.now();
    var row;
    try {
      var hdu = M.findImageHDU(buf);
      var d = hdu.compressed ? M.decodeTileCompressed(buf, hdu, function () {}, null)
                             : M.toNormalisedFloat(buf, hdu, function () {});
      row = { veredito: 'aceita', dims: d.w + 'x' + d.h + 'x' + d.planes };
    } catch (e) {
      row = { veredito: 'rejeita', kind: (e && e.kind) || (e && e.constructor && e.constructor.name) || 'sem-kind',
              mensagem: String((e && e.message) || e) };
    }
    // Sub-millisecond everywhere today. Recorded because "it stopped" is half
    // the claim: a file that hangs the tab fails differently from one that
    // errors, and the number is what tells them apart.
    row.ms = Math.round(performance.now() - t0);
    row.bytes = buf.byteLength;
    out[f] = row;
  }

  var body = new Blob([JSON.stringify({ casos: out }, null, 2)]);
  var ab = await body.arrayBuffer();
  await fetch('/save/malformed.results.json', { method: 'POST', body: ab });
  return { casos: names.length, arquivo: 'malformed.results.json', bytes: ab.byteLength };
};

// Re-runs the chain with parameters that are not the defaults, through the same
// requestRun the interface uses. Waits on the result panel rather than on a
// promise, because requestRun is fire-and-forget by design: the host is a UI and
// its answer arrives as a repainted screen.
window.__rerun = function (over) {
  var params = {}, k;
  for (k in window.__state.defaults) params[k] = window.__state.defaults[k];
  for (k in over) params[k] = over[k];
  window.__state.diag = null;
  requestRun(params, 'full');
  return new Promise(function (resolve, reject) {
    var waited = 0;
    var iv = setInterval(function () {
      if (window.__state.diag) { clearInterval(iv); resolve('ok'); return; }
      if (document.getElementById('err').classList.contains('on')) {
        clearInterval(iv);
        reject(new Error(document.getElementById('errtitle').textContent));
        return;
      }
      if ((waited += 250) > 120000) { clearInterval(iv); reject(new Error('rerun timed out')); }
    }, 250);
  });
};


/* ------------------------------------------------------------------ *
 * A salvaguarda de estabilidade, exercitada nos dois lados
 *
 * A regra dos ganhos e: um erro de 10% no ceu pode mover qualquer ganho em no
 * maximo 5%. Depois que ela substituiu a regra dos 3x, NENHUM fixture a faz
 * disparar -- todos ficam entre 0,03% e 1,3%. Uma salvaguarda que nunca
 * dispara e uma salvaguarda que ninguem verificou, e isso ja custou uma
 * sessao aqui com os quatro zeros do `rejected-edge`.
 *
 * Somar uma constante ao quadro nao muda `above` (o pedestal e a mediana
 * estelar sobem juntos) mas AUMENTA a sondagem, que e 10% do pedestal. E o
 * caso fisico exato que a regra existe para pegar: ceu alto contra estrela
 * fraca. A varredura tem que passar de APLICA para RECUSA, e a sensibilidade
 * tem que crescer monotonicamente ate la.
 * ------------------------------------------------------------------ */
window.__captureSafeguards = async function () {
  var src = document.getElementById('pipeline-src').textContent;
  var shim = { onmessage: null, postMessage: function () {} };
  new Function('self', src + ';self.__S={findImageHDU:findImageHDU,' +
    'toNormalisedFloat:toNormalisedFloat,Image:Image,' +
    'stepBackground:stepBackground,stepColourCal:stepColourCal};')(shim);
  var S = shim.__S;

  var passos = [0, 0.05, 0.10, 0.15, 0.20, 0.30];
  var casos = [];
  for (var i = 0; i < passos.length; i++) {
    var C = passos[i];
    var buf = await fetch('/f/test/fixtures/fixture-gradient.fit').then(function (r) { return r.arrayBuffer(); });
    var hdu = S.findImageHDU(buf);
    var d = S.toNormalisedFloat(buf, hdu, function () {});
    var dat = new Float32Array(d.data);
    for (var k = 0; k < dat.length; k++) dat[k] += C;
    var img = new S.Image(dat, d.w, d.h, d.planes);
    var r1 = [];
    var bg = S.stepBackground(img, { samplesPerRow: 12, boxSize: 25, tolerance: 1.0,
      edgeMargin: 0.02, smoothing: 0.10, correction: 'subtract',
      pedestal: 'model-median', scale: 1, stride: 1 }, function (x) { r1.push(x); });
    var r2 = [];
    S.stepColourCal(bg, { backgroundNeutralise: true, starSigma: 12.0, starMax: 0.85,
      minStarPixels: 2000, extendedWindow: 25, extendedFrac: 0.50,
      reference: 'green', stride: 1 }, function (x) { r2.push(x); });
    var st = r2[0].stars;
    casos.push({
      ceuAdicionado: C,
      pedestal: st.pedestals ? st.pedestals[1] : null,
      sensibilidade: st.gainSensitivity,
      canal: st.gainSensitivityChannel,
      veredito: st.applied ? 'aplica' : 'recusa',
      ganhos: r2[0].gains || null
    });
  }
  var body = new Blob([JSON.stringify({ casos: casos }, null, 2)]);
  var ab = await body.arrayBuffer();
  await fetch('/save/safeguards.results.json', { method: 'POST', body: ab });
  return { casos: casos.length, arquivo: 'safeguards.results.json' };
};

window.__captureAll = async function () {
  var out = {};
  for (var i = 0; i < window.__GOLDEN.length; i++) {
    var name = window.__GOLDEN[i][0], url = window.__GOLDEN[i][1], over = window.__GOLDEN[i][2];
    var r = await window.__loadFromURL(url, { now: window.__GOLDEN_DATE });
    if (r !== 'ok') throw new Error(name + ': ' + url + ' failed to load');
    if (over) await window.__rerun(over);
    out[name] = await window.__capture(name);
  }
  out['malformed'] = await window.__captureMalformed();
  out['safeguards'] = await window.__captureSafeguards();
  return out;
};
